# Generated by Django 2.1.1 on 2020-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('mail', models.CharField(default='gigi@gmail.com', max_length=255, unique=True)),
                ('password', models.CharField(default='ciao', max_length=30)),
            ],
        ),
    ]
