# Generated by Django 2.1.1 on 2020-02-07 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrelloUtente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=6)),
                ('descrizione', models.CharField(max_length=255)),
                ('sconto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('prezzo', models.FloatField()),
                ('magazzino', models.IntegerField()),
                ('immagine', models.CharField(max_length=2083)),
            ],
        ),
        migrations.AddField(
            model_name='carrelloutente',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_prodotti.Prodotto'),
        ),
    ]
